version: "3.8" # Docker Composeのバージョンを指定

services:
 nextjs-dev:
  build:
   context: . # Dockerfileがあるディレクトリ (カレントディレクトリ)
   dockerfile: Dockerfile # Dockerfileの名前
  container_name: iteract-web # コンテナの名前 (任意)
  ports:
   - "3000:3000" # ホストOSのポート:コンテナのポート
  volumes:
   - .:/snd/dev/iteract-web # ホストOSのプロジェクトルート:コンテナの作業ディレクトリ (ソースコードの同期)
   - /snd/dev/iteract-web/node_modules # node_modules はコンテナ内のものを使用する (パフォーマンス向上のため)
   - /snd/dev/.next # .next ディレクトリもコンテナ内のものを使用する
  environment:
   - NODE_ENV=development # 開発モードを指定
  # 起動し続けるための設定 (エラーでコンテナが終了するのを防ぐ)
  stdin_open: true
  tty: true
