name: Deploy Next.js to Cloudflare Workers with OpenNext

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Install OpenNext Cloudflare adapter
        run: pnpm add @opennextjs/cloudflare wrangler --save-dev

      - name: Create wrangler.toml
        run: |
          cat > wrangler.toml << EOF
          main = ".open-next/worker.js"
          name = "${{ github.event.repository.name }}"
          compatibility_date = "2025-04-25"
          compatibility_flags = ["nodejs_compat"]
          
          [assets]
          directory = ".open-next/assets"
          binding = "ASSETS"
          EOF

      - name: Build application with OpenNext
        run: pnpm exec opennextjs-cloudflare

      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: pnpm exec wrangler deploy
